### ISSUE TITLE
uploader for Linux

### ISSUE THREAD

**Issue by simonchen007** [ngohaibac/Quectel_USB_Serial_Driver#1]
hello,

is there firmware uploader for Linux ?

**Comment by ptchiang** [comment]
Hello,

There is QFlash tool for Linux to update firmware for Quectel module.
You could find it in below link:
https://reurl.cc/D1MYEN

Requirement to run QFlash:
1.  Remove qcserial.ko
$ sudo rm /lib/modules/`uname -r`/kernel/drivers/usb/serial/qcserial.ko 

2.  Remove modemmanager
$ sudo dpkg --purge modemmanager

3. Enter "LTE_LTE-A_QFlash_Linux_Android_V2.0" and type "make" to build QFlash tool.

4. Refer document "Quectel_LTE_LTE-A_QFlash_Linux_Android_User_Guide_V2.0.pdf" for more information.

**Comment by simonchen007** [comment]
thank you very much

**Comment by simonchen007** [comment]
why need to remove the driver ? this package is driver included ?

**Comment by spit4520** [comment]
Why do we need to remove the driver in order to run the tool? I thought we are supposed to install the driver first

**Comment by spit4520** [comment]
I have followed this thread on the forum, but the user does not publish their tools or explain their fix.

https://forums.quectel.com/t/bg96-qflash-for-linux-doesnt-seem-to-work/3202/7

I am in a similar state where I am unable to upload and debug my application without blindly guessing and running the risk of bricking my board. I have gotten the Qflash2.0 for Android tool to compile and run, but I am left with choosing either firehose or fastboot and few descript options.

I would like to figure out a working path for development on Linux as in production our CI/CD platform will output a binary and then push it to and update server.
