### ISSUE TITLE
USB Device Discovery PlatformIO Issue

### ISSUE THREAD

**Issue by spit4520** [ngohaibac/Quectel_USB_Serial_Driver#2]
Hello,

I am currently on Ubuntu 18.04.4 and I am trying to upload to a BG96 module. I have installed the driver and I am attempting to upload to it, but I receive a "connect no response" error when I attempt to connect to the "DM-Port" 

The device's list is displayed as such:

/dev/ttyUSB4 | Qualcomm CDMA Technologies MSM | USB VID:PID=2C7C:0296 SER=67a0116c LOCATION=1-1.2:1.3
-- | -- | --
/dev/ttyUSB3 | Qualcomm CDMA Technologies MSM | USB VID:PID=2C7C:0296 SER=67a0116c LOCATION=1-1.2:1.2
/dev/ttyUSB2 | Qualcomm CDMA Technologies MSM | USB VID:PID=2C7C:0296 SER=67a0116c LOCATION=1-1.2:1.1
/dev/ttyUSB1 | Qualcomm CDMA Technologies MSM | USB VID:PID=2C7C:0296 SER=67a0116c LOCATION=1-1.2:1.0
/dev/ttyUSB0 | USB Serial Converter | USB VID:PID=0403:6001 SER=FTB6AQ39 LOCATION=3-4

As you can see all of the devices (except the usb hub) are recognized as a generic "CDMA"/"MSM" device. I am able to connect over USB3 to the AT command interface, but I cannot get anything else to work.

I am also unable to use the Qflash tool, When I attempt to compile the tool it complains of "error: unable to find string literal operator ‘operator""fmt’ with ‘const char [6]’, ‘long unsigned int’ arguments" at around 100 different places in the code.

I am fine with using the graphical or CLI tool to move the build image from PlatformIO to the device directly, but I am currently unable to get anything to communicate properly.

Thanks

S

**Comment by bacnh85** [comment]
Hi @spit4520,

What is your BG96 FW version are you using ?
