### ISSUE TITLE
porting to latest Ubuntu 16.04?

### ISSUE THREAD

**Issue by zhangwei-arm** [ngohaibac/Quectel_USB_Serial_Driver#3]
Hi, I found that this is very useful,  I am using EC20 for my project.  However, by checking out the 4.15.0 it doesn't work on the latest Ubuntu 16.04 installation. Could you pls provide a branch that works with the latest kernel version which is, in my case, is linux-image-4.15.0-96-generic?  Thank you.

**Comment by bacnh85** [comment]
What is your issue with 4.15.0-96 ? That 4.15 branch should work out of the box.

**Comment by zhangwei-arm** [comment]
Not really, if you look at the kernel code, it's quite different.

**Comment by bacnh85** [comment]
@zhangwei-arm can you show me the error when compiling the kernel modules ?
