### ISSUE TITLE
BG95

### ISSUE THREAD

**Issue by tiego-007** [ngohaibac/Quectel_USB_Serial_Driver#5]
good day, can I also use the BG95 modem on a Raspian RPI3 + with your installer? Unfortunately, the USB devices are not displayed to me. Many Thanks

**Comment by bacnh85** [comment]
Hi @tiego-007,

Pls refer to my debug steps: https://bacnh.com/quectel-linux-usb-drivers-troubleshooting/ to identify steps that you can debug if module is detected by your OS.
